ALTER TABLE "accounts"
ADD COLUMN IF NOT EXISTS "role" VARCHAR(50) NOT NULL DEFAULT 'admin',
ADD COLUMN IF NOT EXISTS "sector" VARCHAR(100),
ADD COLUMN IF NOT EXISTS "primaryChannels" TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[];