ALTER TABLE "accounts"
ADD COLUMN IF NOT EXISTS "twoFactorEnabled" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN IF NOT EXISTS "twoFactorCode" VARCHAR(10),
ADD COLUMN IF NOT EXISTS "twoFactorCodeExpiry" TIMESTAMP(3);